apiVersion: v1
kind: Service
metadata:
  name: clipboard-landing-page-master
  namespace: default
spec:
  selector:
    app: clipboard-landing-page-master-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
